#!/usr/bin/env python3
"""PyFEX Dormant Function Analysis driver.

Reads a DEFINED/CALLED log produced by the PyFEX interpreter (via
DORMANT_FUNC_LOG_FILE), computes the set of defined-but-never-called
callables in the target script's scope, and invokes each one in a
fresh PyFEX subprocess so its body runs under crash recovery and
produces execution traces.

Usage (orchestrator):
    python3 tools/dfa_driver.py <log_file> <target_script>

Environment:
    PYFEX_INTERPRETER     - path to the PyFEX python binary
                            (default: PyFEX-core/python relative
                            to this file's parent).
    DFA_INVOKE_CAP        - maximum number of dormant functions to
                            invoke per run (default: 32).
    DFA_INVOKE_LOG        - path to a log file the orchestrator writes
                            per-invocation status to. Optional.

Per-target flow:
    1. The orchestrator generates a tiny wrapper script in the target's
       own directory.
    2. The wrapper imports the target file via importlib and resolves
       the qualname.
    3. The wrapper reads the signature and supplies a DummyObject for
       every required parameter UP FRONT, so the call boundary is
       crossed and the dormant body actually runs. (A zero-arg call
       would raise a missing-argument TypeError that crash recovery
       turns into a returned DummyObject at CALL_FUNCTION -- the body
       would never run, yet the call would look "invoked".)
    4. For class-method qualnames (Cls.method), the wrapper instantiates
       Cls using None (NOT DummyObjects) for required __init__ args -- a
       DummyObject passed to a type is short-circuited before the
       constructor runs -- then invokes the method on the real instance.

Because PyFEX's crash recovery only activates for files within the
target's scope, the wrapper lives next to the target so it is in
scope. Subprocesses run with CRASH_RECOVERY_ENABLE=1 and
PYFEX_SCOPE_DIR set to the target directory.
"""

from __future__ import annotations

import os
import shlex
import sys
import textwrap
from pathlib import Path


DEFAULT_INVOKE_CAP = 32


def parse_log(log_path: str):
    """Parse a DEFINED/CALLED log.

    Each line has the form:
        DEFINED qualname name filename:lineno
        CALLED  qualname name filename:lineno
    filename may contain spaces, but rsplit(':', 1) peels off the line
    number unambiguously because bytecode line numbers are non-negative.
    Returns (defined_dict, called_set) where defined_dict maps
    qualname -> (filename, lineno).
    """
    defined: dict[str, tuple[str, int]] = {}
    called: set[str] = set()
    with open(log_path) as fp:
        for raw in fp:
            line = raw.rstrip("\n")
            if not line:
                continue
            parts = line.split(" ", 3)
            if len(parts) != 4:
                continue
            kind, qualname, _name, loc = parts
            if ":" not in loc:
                continue
            filename, lineno_str = loc.rsplit(":", 1)
            try:
                lineno = int(lineno_str)
            except ValueError:
                continue
            if kind == "DEFINED":
                defined[qualname] = (filename, lineno)
            elif kind == "CALLED":
                called.add(qualname)
    return defined, called


def compute_dormant(defined, called, scope, cap):
    """Return [(qualname, defining_file), ...] for callables DEFINED within
    ``scope`` -- a single ``.py`` file, or any file under a directory --
    that were never CALLED and are not private (leading underscore). Carrying
    the defining file lets the replay import the right module per dormant, so
    a whole package's dormant callables can be replayed in one pass."""
    scope_abs = os.path.abspath(scope)
    scope_is_dir = os.path.isdir(scope_abs)
    result = []
    for qualname, (filename, _lineno) in defined.items():
        if qualname in called:
            continue
        try:
            fabs = os.path.abspath(filename)
        except Exception:
            continue
        if scope_is_dir:
            if fabs != scope_abs and not fabs.startswith(scope_abs + os.sep):
                continue
        elif fabs != scope_abs:
            continue
        leaf = qualname.rsplit(".", 1)[-1]
        if leaf.startswith("_"):
            continue
        result.append((qualname, fabs))
        if len(result) >= cap:
            break
    return result


WRAPPER_TEMPLATE = textwrap.dedent('''\
    """PyFEX DFA wrapper -- autogenerated, safe to delete."""
    import importlib.util
    import inspect
    import sys


    TARGET = {target_repr}
    QUALNAME = {qualname_repr}
    MARKER = {marker_repr}


    def _note(tag, detail=""):
        if MARKER is None:
            return
        try:
            with open(MARKER, "a") as fp:
                fp.write(tag + ":" + QUALNAME + (":" + detail if detail else "") + "\\n")
        except BaseException:
            pass


    def _make_dummy():
        """Produce a DummyObject via crash recovery on an undefined name."""
        try:
            return __pyfex_dfa_dummy_source__  # noqa: F821
        except BaseException:
            return None


    def _synthesise_args(fn):
        """Build (args, kwargs) of DummyObjects for every REQUIRED parameter.
        Returns (None, None) if the signature can't be introspected.

        Built with operators, NOT list.append/dict-item calls: a DummyObject
        passed as a *call argument* to an out-of-scope callable (e.g.
        list.append) is intercepted by crash recovery -- the call is
        short-circuited to a returned dummy and the append silently no-ops.
        ``[dummy] * n`` and a dict comprehension build the containers with
        bytecode ops instead, so the dummies actually land in them. The dummy
        is also made on its own line so its recovery completes cleanly before
        the container is built."""
        try:
            sig = inspect.signature(fn)
        except (TypeError, ValueError):
            return None, None
        dummy = _make_dummy()
        n_pos = 0
        kw_names = []
        for p in sig.parameters.values():
            if p.default is not p.empty:
                continue
            if p.kind in (p.POSITIONAL_ONLY, p.POSITIONAL_OR_KEYWORD):
                n_pos += 1
            elif p.kind == p.KEYWORD_ONLY:
                kw_names.append(p.name)  # p.name is a str, not a dummy: safe
            # VAR_POSITIONAL / VAR_KEYWORD accept zero, so require nothing.
        args = [dummy] * n_pos
        kwargs = {{name: dummy for name in kw_names}}
        return args, kwargs


    def _invoke(fn):
        # Synthesise the required arguments UP FRONT and pass them directly.
        # Calling fn() with too few args first would raise a missing-argument
        # TypeError that crash recovery turns into a returned DummyObject at
        # CALL_FUNCTION -- the body would never run, yet the call would look
        # "invoked". Supplying a dummy for every required parameter means the
        # call boundary is crossed and the dormant body actually executes.
        args, kwargs = _synthesise_args(fn)
        try:
            if args is None:
                return fn(), True  # signature unavailable; best effort
            return fn(*args, **kwargs), True
        except BaseException:
            return None, False


    def _instantiate(cls):
        # Instantiate a dormant class for method replay. Use None (NOT
        # DummyObjects) for required constructor args: a DummyObject passed to
        # a class (a type) is short-circuited by crash recovery before the
        # constructor runs, leaving a dummy instance whose methods never
        # execute. None crosses the constructor call cleanly, so the real
        # instance -- and then its dormant method -- actually run.
        try:
            sig = inspect.signature(cls)
        except (TypeError, ValueError):
            try:
                return cls(), True
            except BaseException:
                return None, False
        n_pos = 0
        kw_names = []
        for p in sig.parameters.values():
            if p.default is not p.empty:
                continue
            if p.kind in (p.POSITIONAL_ONLY, p.POSITIONAL_OR_KEYWORD):
                n_pos += 1
            elif p.kind == p.KEYWORD_ONLY:
                kw_names.append(p.name)
        args = [None] * n_pos
        kwargs = {{name: None for name in kw_names}}
        try:
            return cls(*args, **kwargs), True
        except BaseException:
            return None, False


    def main():
        spec = importlib.util.spec_from_file_location("dfa_target", TARGET)
        if spec is None or spec.loader is None:
            _note("load_fail")
            return
        mod = importlib.util.module_from_spec(spec)
        try:
            spec.loader.exec_module(mod)
        except BaseException:
            _note("exec_module_fail")

        parts = QUALNAME.split(".")
        if len(parts) == 1:
            fn = getattr(mod, parts[0], None)
            if fn is None:
                _note("not_found")
                return
            _, ok = _invoke(fn)
            _note("invoked" if ok else "failed")
            return

        cls = getattr(mod, parts[0], None)
        if cls is None:
            _note("class_not_found")
            return
        instance, ok = _instantiate(cls)
        if not ok or instance is None:
            _note("instantiate_fail")
            return
        method = getattr(instance, ".".join(parts[1:]), None)
        if method is None:
            _note("method_not_found")
            return
        _, ok = _invoke(method)
        _note("invoked" if ok else "failed")


    if __name__ == "__main__":
        main()
''')


def default_interpreter():
    here = Path(__file__).resolve().parent
    candidate = here.parent / "PyFEX-core" / "python"
    return str(candidate)


def invoke_one(interp, defining_file, qualname, marker, scope_dir):
    target_abs = os.path.abspath(defining_file)
    wrapper_dir = os.path.dirname(target_abs)
    slug = qualname.replace(".", "_")
    wrapper_path = Path(wrapper_dir) / f"_dfa_invoke_{slug}_{os.getpid()}.py"

    content = WRAPPER_TEMPLATE.format(
        target_repr=repr(target_abs),
        qualname_repr=repr(qualname),
        marker_repr=repr(marker) if marker else "None",
    )
    wrapper_path.write_text(content)

    env_prefix = " ".join(
        f"{k}={shlex.quote(v)}" for k, v in {
            "CRASH_RECOVERY_ENABLE": "1",
            "PYFEX_SCOPE_DIR": scope_dir,
        }.items()
    )
    cmd = (
        f"{env_prefix} {shlex.quote(interp)} {shlex.quote(str(wrapper_path))} "
        f">/dev/null 2>&1"
    )
    try:
        os.system(cmd)
    finally:
        try:
            wrapper_path.unlink()
        except FileNotFoundError:
            pass


def main(argv):
    if len(argv) < 3:
        sys.stderr.write(
            "usage: dfa_driver.py <log_file> <target_script_or_package_dir>\n"
        )
        return 2
    log_path = argv[1]
    scope = argv[2]  # a single target .py file OR a package directory
    cap = int(os.environ.get("DFA_INVOKE_CAP", str(DEFAULT_INVOKE_CAP)))

    defined, called = parse_log(log_path)
    dormant = compute_dormant(defined, called, scope, cap)

    interp = os.environ.get("PYFEX_INTERPRETER") or default_interpreter()
    marker = os.environ.get("DFA_INVOKE_LOG")

    scope_abs = os.path.abspath(scope)
    scope_dir = scope_abs if os.path.isdir(scope_abs) else os.path.dirname(scope_abs)

    if not dormant:
        sys.stdout.write("[dfa] no dormant callables in target scope\n")
        return 0

    sys.stdout.write(
        f"[dfa] invoking {len(dormant)} dormant callable(s) under {interp}\n"
    )
    for qualname, defining_file in dormant:
        sys.stdout.write(f"[dfa]   {qualname}\n")
        invoke_one(interp, defining_file, qualname, marker, scope_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
